
http://localhost:8001/api/v1/categories

#######################################

http://localhost:8001/api/v1/questions/1

#######################################

http://localhost:8001/api/v1/questions
#######################################

http://localhost:8001/api/v1/languages

#######################################

http://localhost:8001/api/v1/categories/2/questions

#######################################

http://localhost:8001/api/v1/users/2


#####################
POST http://localhost:8001/api/v1/login
Content-Type: application/json

{
    "email":"bo@gmail.com",
    "password": "password"
}

#####################
POST http://localhost:8001/api/v1/logout


###########################
DELETE  http://localhost:8001/api/v1/answers/1

#####################
POST http://localhost:8001/api/v1/questions
Content-Type: application/json

{
    "category_id":1,
    "content":"does this shit work?",
    "answers":
    [
        {
            "code":"a[]",
            "language_id":2,
            "text":"yes"},
        {
            "code":"c[]",
            "language_id":1,
            "text":"yeah"
        }
    ]
}