
http://localhost:8001/api/v1/categories

#######################################

http://localhost:8001/api/v1/categories/2/questions

#######################################

http://localhost:8001/api/v1/users/2


#####################
POST http://localhost:8001/api/v1/login
Content-Type: application/json

{
    "email":"bo@gmail.com",
    "password": "password"
}

#####################
POST http://localhost:8001/api/v1/logout